name: 'Debug workflow'
on: [push]

jobs:
  build:
    name: SetSecret
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: npm install
      - run: npm run build
      - uses: ./.github/actions/setsecret-action
        with:
          data: '{"Secrets": [ {"name": "HelloWorld1", "value": "avalue"}, {"name": "HelloWorld2", "value": "anothervalue"}]}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SETSECRET_USER_TOKEN: ${{ secrets.SETSECRET_USER_TOKEN }}
