name: 'Debug workflow'
on: [push]
env:
  andy: helloworld

jobs:
  build:
    name: SetSecret
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: npm install
      - run: npm run build
      - uses: ./.github/actions/maskvariable-action
        with:
          variable-name: 'andy'
      - run: echo "::set-env name=andy::world" 
